version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t php 7.1
      - run: docker save php
