version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/php.tar
      - run: docker load -i /caches/php.tar | true
      - run: docker build --cache-from=php -t php .
      - run: docker save -o /caches/php.tar php
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
