version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --cache-from=php -t newridetech/php .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker tag newridetech/php newridetech/php:7.1
      - run: docker push newridetech/php:7.1
