version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /tmp/php.tar
      - run: |
          set +o pipefail
          docker load -i /tmp/php.tar | true
      - run: docker build --cache-from=php -t newridetech/php .
      - run: docker save -o /tmp/php.tar newridetech/php
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/app.tar
      - run: docker tag newridetech/php newridetech/php:${CIRCLE_SHA1}
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push newridetech/php:${CIRCLE_SHA1}
